#!/usr/bin/perl

package placeholder;

use strict;
use warnings;

use lib "./lib";
use lib "/usr/share/perl5";

use IO;
use CGI;

my $cgi = $CGI->new;

sub placeholder {
  my $style = &read_all("./style.css");
  my $content = &$_[0]($cgi);

  print <<EOT
  Content-Type: text/html

  <!-- -->

  <!DOCTYPE HTML>
  <html>
    <head>
      <style>
        $style
      </style>
    </head>

    <body>
      <header class="header">
        <h1 class="header__logo">
          <span class="header__logo__brand_name">
            RaB2WoPerOX
          </span>
          <span class="header__logo__brand_catchcopy">
            <span>
              Random bulletin board
            </span>
            <span>
              working on Perl on XAMPP
            </span>
          </span>
        </h1>
        <button class="header__new_post">
          New post?
        </button>

        <main>
          
        </main>

      </header>
    </body>
  </html>

  <!--
  EOT
  ;
}

# vim: set ft=html: -->
  
  
  
  
  
  
  
  
  
  
