#!/usr/bin/perl

# <!--

use strict;
use warnings;

use CGI;

use Data::Dumper;

use domain::Post;
use types::Result;
use repository::PostRepository;

use view::placeholder;

local $Data::Dumper::Terse = 1;

###########################################################3

&placeholder::apply("post", sub {
  my $id = $_[0]->param("id");
  my %maybe_post = &PostRepository::get_by_id($id);

  if(!Result::is_ok(\%maybe_post)) {
    return "Could not find the post";
  }
  my %post = Result::unwrap(\%maybe_post);

  return <<EOF
<!-- -->
  <article class="article">
    <section>
      <h2 class="article__title">
        ${\(Post::title(\%post))}
      </h2>
      <span class="article__author">
        Posted by ${\(Post::author(\%post))}
      </span>
    </section>
    <section>
      ${\(Post::content(\%post))}
    </section>
  </article>
<!--
EOF
;})

# vim: set ft=html: -->
