#!/usr/bin/perl

# <!--

use strict;
use warnings;

use CGI;

use domain::Post;
use types::Result;
use repository::PostRepository;

use view::placeholder;

###########################################################3

&placeholder::apply("post", sub {
  my $id = $_[0]->param("id");
  my %post = &PostRepository::get_by_id($id);

  if(!Result::is_ok(\%post)) {
    return "Could not find the post";
  }

  my %raw_post = Result::unwrap(\%post);

  my %self_unwrap = %post{"payload"};
  my $aut = $self_unwrap{"author"};
  my $author = Post::author(\%raw_post);
  my $content = Post::content(\%raw_post);

  return <<EOF
<!-- -->
  $aut
<!--
EOF
;})

