#!/usr/bin/perl

use strict;
use warnings;

use domain::Post;
use repository::PostRepository;
use view::placeholder;

use CGI;

&placeholder::apply("create-new-post", sub {
  my $cgi = $_[0];

  my $author = $cgi->param("author");
  my $content = $cgi->param("content");

  my $id = &PostRepository::add(&Post::new($author, $content));

  return <<EOF
Content-Type: text/html

$id
EOF
});
