#!/usr/bin/perl

use strict;
use warnings;

use placeholder;

use domain::Post;
use repository::PostRepository;

use CGI;

placeholder("create-new-post", sub {
  my $cgi = $_[0];

  my $author = $cgi->param("author");
  my $content = $cgi->param("content");

  my $id = &PostRepository::post_new(&Post::post_def($author, $content));

  return <<EOF
Content-Type: text/html

$id
EOF
});
